import { Geist, Geist_Mono } from "next/font/google";
import SimpleNavbar from "./components/SimpleNavbar";
import DarkFooter from "./components/DarkFooter";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Coding Event Night",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SimpleNavbar />
        {children}
        <DarkFooter />
      </body>
    </html>
  );
}
